### PR TITLE
Change biblio entry for [arnold-longley-2020]

### PR DESCRIPTION
**Pull request by pchampin**
address #100

@dlongley are you ok with characterizing this document as a "Technical Report"?

### CODE REVIEW

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
> @dlongley are you ok with characterizing this document as a "Technical Report"?

@pchampin, would it help to publish this as a W3C NOTE or Member Submission (eventually)? I have no idea if there is a nice LaTeX->ReSpec renderer... :)

**Comment by pchampin** [comment]
> @pchampin, would it help to publish this as a W3C NOTE or Member Submission (eventually)? 

The first issue at hand, IMO, is to make the biblio entry accurate and not misleading (arguably, it does not check those boxes in it scurrent form). This can be fixed without changing anything to the document itself.

That being said, it might make sense to publish this document as a Member Submission (I don't think a W3C Note is appropriate here). But that would take some time, and we don't want to stale the charter on this, do we?

> I have no idea if there is a nice LaTeX->ReSpec renderer... :)

Well, that too may take some time :)

**Comment by msporny** [comment]
> But that would take some time, and we don't want to stale the charter on this, do we?

Yes, agreed, I was mostly just offering it as something we might do in the future, once the WG was formed. Agree that this PR can be merged as-is.

**Comment by dlongley** [comment]
@pchampin,

> are you ok with characterizing this document as a "Technical Report"?

Yes, whatever it takes to help move the work forward.

**Review by dlongley — APPROVED** [review]

**Pull request merged**
